Runs the NER pipeline on several articles to evaluate the accuracy.

## Imports & setup

In [ ]:
# These commands auto-reload all imported modules, so that you don't have to rerun `helper_functions.py` if you make changes to it.

# load the autoreload extension
%load_ext autoreload 

# auto-reload all modules
%autoreload 2

In [ ]:
from flair.models import SequenceTagger
import pandas as pd
import ner

In [ ]:
# Initialize NER models

date_tagger = SequenceTagger.load("flair/ner-english-ontonotes-large") # 18-class Flair model that can extract dates and times
loc_tagger = SequenceTagger.load("Saisam/Inquirer_ner_loc") # initialize the model

## Load data

In [ ]:
df = pd.read_csv("police_reports.csv") # all texts
df.head()

We will filter the dataframe to only texts that are less than 3000 characters, since it takes too much computational time to run NER on long texts.

In [ ]:
small_df = df.loc[df["text"].str.len() < 3000].reset_index(drop=True)[:20].sort_values(by="text") # The dataframe to test NER on. Get only the first 20 texts
small_df

The first 20 rows have a variety of documents, such as articles, court cases, and other legal documents. So, we will see how NER performs across many different types of text.

## Test NER models

In [141]:
dates_df = ner.run_ner_on_dataframe(date_tagger, small_df, conf_thresh=None, entity_tag="DATE", splitting_method="every_n_words", n = 100) # tag all dates

In [142]:
dates_df

,text,text_id,entities,scores
0,Home Legislative File 2021-01132 RCA Legal s...,0,2021-10-20,0.999993
1,Home Legislative File 2021-01132 RCA Legal s...,0,2021-12-04,0.999784
2,Home Legislative File 2021-01132 RCA Legal s...,0,2021-12-04,0.999633
3,"Hennepin County 300 South Sixth Street, Minne...",1,2021-12-21,0.999994
4,4/12/2021 Officers ID'd in Brooklyn Center fat...,11,2019-09-06,0.999989
5,4/12/2021 Officers ID'd in Brooklyn Center fat...,11,2019-09-06,0.999992
6,4/12/2021 Officers ID'd in Brooklyn Center fat...,11,2019-09-06,0.999985
7,4/12/2021 Officers ID'd in Brooklyn Center fat...,11,2021-04-12,0.999988
8,4/12/2021 Officers ID'd in Brooklyn Center fat...,11,2021-04-12,0.999994
9,Home Legislative File 2022-00239 RCA Legal S...,14,2022-03-07,0.999994
10,Home Legislative File 2022-00239 RCA Legal S...,14,2022-03-18,0.999938
11,Home Legislative File 2021-01180 RCA Legal s...,17,2021-11-03,0.999994
12,Home Legislative File 2021-01180 RCA Legal s...,17,2021-12-04,0.999946
13,Home Legislative File 2021-01180 RCA Legal s...,17,2021-12-04,0.999888
14,Minneapolis Police Officers: 350 S. 5th St. ...,25,NaN,NaN
15,OAO450 (Rev. 5/85) Judgment in a Civil Case ...,26,2014-11-24,0.999993
16,OAO450 (Rev. 5/85) Judgment in a Civil Case ...,26,2014-11-24,0.999994
17,City of Minneapolis Request for Committee Act...,31,2015-09-08,0.999992
18,4/5/2021 Another MPD officer accused of using ...,32,2013-08-01,0.999993
19,4/5/2021 Another MPD officer accused of using ...,32,2018-03-08,0.999993
20,4/5/2021 Another MPD officer accused of using ...,32,2021-04-05,0.999986
21,3/1/2021 MPD rehires officer fired over domest...,38,2012-05-18,0.999993
22,3/1/2021 MPD rehires officer fired over domest...,38,2021-03-01,0.999984
23,/ MPR News Notes on the news from the Twin Cit...,43,2011-12-13,0.999988
24,OAO450 (Rev. 5/85) Judgment in a Civil Case ...,45,2004-09-16,0.999981
25,OAO450 (Rev. 5/85) Judgment in a Civil Case ...,45,2012-01-23,0.999993
26,2/22/2021 BCA investigation complete in St. Pa...,48,2018-09-19,0.999989
27,2/22/2021 BCA investigation complete in St. Pa...,48,2021-02-22,0.999912
28,2/22/2021 Financial crimes task force is leade...,51,2007-01-26,0.999982
29,2/22/2021 Financial crimes task force is leade...,51,2007-01-26,0.999994
30,2/22/2021 Financial crimes task force is leade...,51,2021-02-22,0.999991
31,Home Legislative File 2022-00178 RCA Legal S...,53,2022-02-22,0.999993
32,Home Legislative File 2022-00178 RCA Legal S...,53,2022-03-18,0.999968
33,Itasca Co. sheriff's deputy charged with video...,57,2013-03-07,0.999986
34,Itasca Co. sheriff's deputy charged with video...,57,2022-11-25,0.99999
35,C C STATE OF MINNESOTA BOARD OF PEACE OFFICER ...,59,1992-10-07,0.999991
36,"By news@duluthnewstribune.com March 20, 2013 1...",60,2013-03-20,0.999991
37,"By news@duluthnewstribune.com March 20, 2013 1...",60,2022-11-25,0.999202
38,"By news@duluthnewstribune.com March 20, 2013 1...",60,2022-11-25,0.970088
39,Home Legislative File 2022-00238 RCA Legal S...,63,2022-03-07,0.999994
40,Home Legislative File 2022-00238 RCA Legal S...,63,2022-03-18,0.99995
41,Too_LongOPCR Case #17-03832 Table of Contents...,65,NaN,NaN

In [143]:
# Detect all locations in the first 20 documents, with no threshold
locations_df = ner.run_ner_on_dataframe(loc_tagger, small_df, conf_thresh=None, entity_tag=None, splitting_method="by_sentences")

In [144]:
locations_df

,text,text_id,entities,scores
0,Home Legislative File 2021-01132 RCA Legal s...,0,City Aorney's Office,0.882122
1,Home Legislative File 2021-01132 RCA Legal s...,0,City of Minneapolis,0.924146
2,Home Legislative File 2021-01132 RCA Legal s...,0,Government,0.511303
3,Home Legislative File 2021-01132 RCA Legal s...,0,Neighborhood,0.571632
4,Home Legislative File 2021-01132 RCA Legal s...,0,Ward Neighborhood Address 1,0.754386
...,...,...,...,...
142,Home Legislative File 2022-00238 RCA Legal S...,63,Ward Neighborhood Address 1,0.918567
143,Too_LongOPCR Case #17-03832 Table of Contents...,65,MPD SIC b,0.78353
144,Too_LongOPCR Case #17-03832 Table of Contents...,65,Minneapolis Police,0.806397
145,Too_LongOPCR Case #17-03832 Table of Contents...,65,Minneapolis Police,0.862937
146,Too_LongOPCR Case #17-03832 Table of Contents...,65,Minnesota State,0.784632

In [145]:
for id in small_df["text_id"]:
    print(f"\n{'~'*50} Text {id}: {'~'*50}")
    ner.print_text(small_df.loc[small_df["text_id"] == id, 'text'].values[0])

    print(f"\n{'-'*50} Dates: {'-'*50}")
    display(dates_df.loc[dates_df["text_id"] == id, ["entities", "scores"]])

    print(f"\n{'-'*50} Locations: {'-'*50}")

    # for this print statement, display an unlimited number of characters in a cell
    with pd.option_context('display.max_colwidth', None):
        display(locations_df.loc[locations_df["text_id"] == id, ["entities", "scores"]])

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Text 43: ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/ MPR News Notes on the news from the Twin Cities Minneapolis cops lauded for
arresting anti- Somali attacker Laura Yuen December 13, 2011, 5:22 PM Remember these guys? Minneapolis
police officers Abdiwahab Ali, left, and Mohamed Abdullahi were profiled in my Sept. 8 piece
on what it's like to be Muslim in Minnesota. Despite working on the front lines
of fighting crime, the two beat cops spoke of additional security measures they faced while
traveling through U.S. airports since the 2001 terrorist attacks. Today, the folks at the Department
of Homeland Security singled them out — to say thank you. The two men, along
with Somali community liaison Officer Jeanine Brudenell and crime-prevention specialist Ahmed Hassan, were honored today
with awards of appreciation for their work on a case resulting in a successful federal
hate-crime / About the blogger prosecution. In May 2010, Ali and Abdullahi, who patrol the
Cedar-Riverside neighborhood, responded to the beating of an 82-year-old Somali man. The attacker punched the
man several times, while yelling anti-Muslim and anti-Somali statements and telling him to go back
to Africa, according to court documents. Although the man ran away that time, Ali and
Abdullahi talked to witnesses. More than two months later, the officers spotted Goerge Loren Thompson,
now 64, who was allegedly chasing a 24-year-old Somali man and threatening to kill him.
The officers arrested Thompson, who police say was drunk and in possession of two handguns.
When Thompson, who is white, learned that Ali and Abdullahi were Somali, police say he
threatened to kill them, too. And to top it off, Thompson worked for the Transportation
Security Administration, which is part of homeland security. Thompson pleaded guilty to the May 2010
incident and was recently sentenced to six months in prison. After accepting the award today,
Abdullahi said the award was humbling. "It's an honor for the job we do in
the community," he said. The attack alarmed many Somali residents because it was so unprovoked,
said Abdiwahab Ali. Immediately after the beating, the elderly victim changed his route and was
afraid to go out, even to the mosque, Ali said. The attacker's sentencing and today's
award ceremony will be appreciated by his community as the police continue to earn its
trust, he said. "It sends a good message from Homeland Security to the people that
a case like this is not going to be tolerated, and it will be prosecuted,"
Ali said. / Laura Yuen lyuen@mpr.org Laura Yuen is a general assignment reporter covering the
Twin Cities as part of MPR News' metro unit. Comments are closed.

-------------------------------------------------- Dates: --------------------------------------------------

      entities    scores
23  2011-12-13  0.999988

-------------------------------------------------- Locations: --------------------------------------------------

                                  entities    scores
61                                  Africa  0.996952
62                         Cedar-Riverside  0.993011
63         Department of Homeland Security  0.992475
64                       Homeland Security  0.882198
65                             Minneapolis  0.990084
66                               Minnesota  0.997117
67                                  Somali  0.774299
68  Transportation Security Administration  0.852598
69                             Twin Cities  0.993049
70                 Twin Cities Minneapolis  0.974132
71                           U.S. airports  0.804555

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Text 48: ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2/22/2021 BCA investigation complete in St. Paul officer-involved shooting of Billy Hughes https://www.fox9.com/news/bca-investigation-complete-in-st-paul-officer-involved-shooting-of-billy-hughes 1/2 BCA
investigation complete in St. Paul officer- involved shooting of Billy Hughes ST. PAUL, Minn. (KMSP)
- Investigators with the Minnesota Bureau of Criminal Apprehension have completed their investigation of the
deadly oÞcer- involved shooting of Billy Hughes and are turning over the case to the
Ramsey County Attorney's OÞce for review. On Aug 5., St. Paul police oÞcers responded to
a 911 call of shots Õred in Hughes' housing complex on the 900 block of
St. Anthony Avenue. Hughes, 45, was armed with a handgun when he was shot and
killed by St. Paul Police OÞcers Vincent Adams and Matthew Jones. A few weeks later,
the St. Paul Police Department released the body camera footage of the shooting. The Ramsey
County Attorney's OÞce will be determining whether to charge the oÞcers involved in the shooting.
When the body camera footage became public, Ramsey County Attorney Jon Choi released a statement
saying he was "conÕdent" the charging decision would come more quickly than other oÞcer- involved
shooting cases his oÞce has previously worked on. Published September 19, 2018 News | FOX
9 Minneapolis-St. Paul | Sponsored Links getspartans.com How to Create an Instant Workforce Ad Content
by Taboola | Schizophrenia | Search Ads | Sponsored Signs of Schizophrenia - Some May
Surprise You Watch Live 2/22/2021 BCA investigation complete in St. Paul officer-involved shooting of Billy
Hughes https://www.fox9.com/news/bca-investigation-complete-in-st-paul-officer-involved-shooting-of-billy-hughes 2/2 This material may not be published, broadcast, rewritten, or redistributed. ©2021 FOX
Television Stations Tophatter.com | Sponsored $6 | Garden Pot f t

-------------------------------------------------- Dates: --------------------------------------------------

      entities    scores
26  2018-09-19  0.999989
27  2021-02-22  0.999912

-------------------------------------------------- Locations: --------------------------------------------------

                                 entities    scores
74                 9 Minneapolis-St. Paul   0.89372
75        900 block of St. Anthony Avenue  0.963473
76                                    BCA  0.552344
77  FOX Television Stations Tophatter.com  0.740435
78                Hughes' housing complex  0.830476
79                              Minnesota  0.990565
80                          Ramsey County  0.948786
81                          Ramsey County  0.549912
82          Ramsey County Attorney's OÞce  0.941988
83                         ST. PAUL, Minn  0.940346
84                               St. Paul  0.993837
85                               St. Paul   0.99223
86                               St. Paul   0.95104
87                               St. Paul  0.900462
88                               St. Paul  0.992537
89             St. Paul Police Department  0.862767

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Text 51: ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2/22/2021 Financial crimes task force is leaderless | MPR News https://www.mprnews.org/story/2007/01/26/financialtaskforce 1/1 Help Minnesota stay
Help Minnesota stay connected! connected! GIVE NOW Financial crimes task force is leaderless St. Paul,
Minn. January 26, 2007 6:42 p.m. (AP) - Minnesota's investigative task force for identity theft
is in limbo after its commander was removed and two investigators quit, a state senator
said Friday. Sgt. Chris Abbas, who led the Minnesota Financial Crimes Task Force, was recalled
to the Minneapolis Police Department, his home agency. Detective Jack Talbot said he resigned after
learning that Abbas was gone. Another investigator also left in the wake of the reassignment.
Sen. Satveer Chaudhary, DFL-Fridley, alleged that Public Safety Commissioner Michael Campion was behind Abbas' removal.
Chaudhary, who sits on the oversight council for the task force, held a Capitol news
conference to call for Abbas and the investigators to be reinstated. Campion said in a
prepared statement that Chaudhary's allegations "falsely mischaracterized the situation" and that Abbas' reassignment was handled
properly and legally. Chaudhary said he wants to more information before the Senate Judiciary Committee
holds a confirmation hearing for Campion, who has led the Public Safety Department since June
2004. That hearing was set for Tuesday, but Senate Judiciary Committee Chairwoman Mee Moua said
Campion had a conflict and the hearing would be rescheduled. Moua said she had heard
no complaints about Campion until Friday, but would consider Chaudhary's concerns. Anoka County Attorney Robert
Johnson, who heads the Minnesota Financial Crimes Oversight Council, said the group aims to have
a new commander within a month. (Copyright 2007 by The Associated Press. All Rights Reserved.)
Your support matters. You make MPR News possible. Individual donations are behind the clarity in
coverage from our reporters across the state, stories that connect us, and conversations that provide
perspectives. Help ensure MPR remains a resource that brings Minnesotans together. Donate today. A gift
of $17 makes a difference. Support MPR News © 2021 Minnesota Public Radio. All rights
reserved.

-------------------------------------------------- Dates: --------------------------------------------------

      entities    scores
28  2007-01-26  0.999982
29  2007-01-26  0.999994
30  2021-02-22  0.999991

-------------------------------------------------- Locations: --------------------------------------------------

                          entities    scores
90                    Anoka County  0.947916
91                    Capitol news  0.765139
92   Minneapolis Police Department  0.860423
93                       Minnesota  0.984601
94                       Minnesota  0.965441
95                       Minnesota  0.970857
96             Minnesota Financial  0.811178
97                Minnesota Public  0.617916
98                     Minnesota's  0.996632
99        Public Safety Department  0.985688
100                 St. Paul, Minn  0.945795

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Text 38: ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
3/1/2021 MPD rehires officer fired over domestic assault charge - StarTribune.com https://www.startribune.com/mpd-rehires-officer-fired-over-domestic-assault-charge/152075585/ 1/1 BLOG MPLS.
() MPD rehires officer fired over domestic assault charge By mjmckinney MAY 18, 2012 —
2:55PM A Minneapolis police officer who had been fired over a domestic abuse allegation was
rehired with back pay Friday, according to his attorney. Mukhtar Abdulkadir, one of the state's
only Somali-American police officers, will forfeit 30 hours of pay as part of the deal,
said attorney Brooke Bass of Bruno Law. Abdulkadir was charged with felony domestic assault and
terroristic threats in early 2011. He was accused of punching his wife and hitting her
with the butt end of his service weapon at their Andover home. Hours after he
was charged, his wife told the Anoka County attorney's office that she had lied and
that the allegations were untrue, despite visible injuries that corroborated her initial story. She said
in her recantation that the couple had been fighting about money, jealousy and his unhappiness
with the marriage when she went to police. He was fired last year by the
Minneapolis police after an internal affairs investigation. He pleaded guilty to a misdemeanor disorderly conduct
charge in October. A felony conviction would have meant Abdulkadir's job, since it automatically strips
an officer of his peace officer's license. The Minneapolis Police Federation hired Bass to represent
Abdulkadir in arbitration proceedings that ended last month.

-------------------------------------------------- Dates: --------------------------------------------------

      entities    scores
21  2012-05-18  0.999993
22  2021-03-01  0.999984

-------------------------------------------------- Locations: --------------------------------------------------

                         entities    scores
55                   Andover home  0.801599
56          Anoka County attorney  0.849901
57                      Bruno Law   0.98982
58                    Minneapolis   0.99207
59  Minneapolis Police Federation  0.851532
60             Minneapolis police  0.776509

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Text 11: ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
4/12/2021 Officers ID'd in Brooklyn Center fatal shooting | MPR News https://www.mprnews.org/story/2019/09/06/officers-idd-in-brooklyn-center-fatal-shooting 1/2 Crime, Law
and Justice O¨cers ID'd in Brooklyn Center fatal shooting Alisa Roth and Riham Feshir September
6, 2019 12:37 p.m. The Minnesota Bureau of Criminal Apprehension in St. Paul. Jeffrey Thompson
| MPR News ¦le Updated: 1:31 p.m. | Posted 7:37 a.m. The Minnesota Bureau of
Criminal Apprehension has identified the officers involved in a fatal shooting last Saturday. The three
officers are: Brandon Akers, who's been with the department for eight years; Steven Holt, a
five-year veteran; and Cody Turner, a 10-year veteran. Brooklyn Center police responded to a domestic
911 call on Aug. 31 involving a man armed with a hammer and a knife.
According to the BCA, when police arrived, they attempted to physically restrain 21-year- old Kobe
Dimock-Heisler. The officers tased him, but the BCA said in a statement that the tasers
were "ineffective."" Shortly after, the BCA says Dimock- Heisler produced a knife. Officers Akers and
Turner then shot Dimock-Heisler, who died at the scene. The officers were wearing body cameras
that captured the incident. No one else was injured and all three officers are on
standard administrative leave. Dimock-Heisler had previously been diagnosed with depression and had been hospitalized several
times this year, after attempting to hurt himself. In March, according to state records, he
was committed to the psychiatric unit of a local hospital; he had stabbed himself in
the belly after getting into a disagreement with his father. It came after medical staff
described him as appearing "increasingly depressed, hopeless, [and] lonely." In January, he threatened to kill
himself and then ran toward a bridge; he was admitted to the hospital after that.
He also reportedly swallowed an entire bottle of an antidepressant medication. Relatives have told KARE
11 that Dimock-Heisler had autism. The family, speaking through an attorney, declined to comment. The
BCA continues to investigate the incident. Once the investigation is complete, the BCA will hand
over its findings to the Hennepin County Attorney's Office for review. Your support matters. You
make MPR News possible. Individual donations are behind the clarity in coverage from our reporters
across the state, stories that connect us, and conversations that provide perspectives. Help ensure MPR
remains a resource that brings Minnesotans together. Donate today. A gift of $17 makes a
difference. Support MPR News © 2021 Minnesota Public Radio. All rights reserved. 4/12/2021 Officers ID'd
in Brooklyn Center fatal shooting | MPR News https://www.mprnews.org/story/2019/09/06/officers-idd-in-brooklyn-center-fatal-shooting 2/2

-------------------------------------------------- Dates: --------------------------------------------------

     entities    scores
4  2019-09-06  0.999989
5  2019-09-06  0.999992
6  2019-09-06  0.999985
7  2021-04-12  0.999988
8  2021-04-12  0.999994

-------------------------------------------------- Locations: --------------------------------------------------

                             entities    scores
11                    Brooklyn Center  0.990574
12                    Brooklyn Center  0.990328
13                    Brooklyn Center  0.989375
14                    Brooklyn Center  0.992216
15  Hennepin County Attorney's Office   0.98395
16                          Minnesota  0.994225
17       Minnesota Bureau of Criminal  0.845466
18                           St. Paul  0.993522

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Text 32: ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
4/5/2021 Another MPD officer accused of using racial slur in Apple Valley fight - Bring
Me The News https://bringmethenews.com/news/another-mpd-officer-accused-of-using-racial-slur-in-bar-fight 1/1 HOME MN NEWS Another MPD oÊcer accused of using racial
slur in Apple Valley ght BMTN STAFF · UPDATED: MAR 8, 2018 · ORIGINAL: AUG
1, 2013 Following a controversial video released this week showing two Minneapolis police of}cers using
racial slurs in a }ght outside a Green Bay bar, the Star Tribune obtained police
records Thursday that described similar behavior by another of}cer. According to the reports, Minneapolis police
of}cers William Woodis, Christopher Bennett and Andrew Allen were at Bogart's Place in Apple Valley
on Nov. 19 last year before a }ght broke out in the parking lot. The
of}cers, who are all white men, were captured on surveillance video chasing down a group
of black men. One of the of}cers knocked a man to the ground, calling him
a "fat (racial expletive)," the Apple Valley police report states. The three of}cers were arrested.
Woodis and Bennet were convicted of disorderly conduct in June, the newspaper reported. Charges against
Allen were dismissed. According to online courts records, Woodis was also convicted of DWI in
June stemming from a May incident. On Wednesday, Minneapolis Police Chief Janeé Harteau apologized for
the behavior of off-duty of}cers Brian Thole and Shawn Powell who were caught on dash
cam video last month using racial slurs during an argument with black men. The two
were put on administrative leave while an internal affairs investigation takes place. A police spokesperson
told the Star Tribune that Woodis, Bennett and Allen are also the subjects of an
open internal affairs investigation. All three currently serve as patrol of}cers in the Second and
Third precincts.

-------------------------------------------------- Dates: --------------------------------------------------

      entities    scores
18  2013-08-01  0.999993
19  2018-03-08  0.999993
20  2021-04-05  0.999986

-------------------------------------------------- Locations: --------------------------------------------------

                          entities    scores
45                    Apple Valley  0.994757
46                    Apple Valley  0.992648
47                    Apple Valley  0.991752
48  Bogart's Place in Apple Valley  0.907101
49                   Green Bay bar  0.861754
50                              MN  0.728004
51                     Minneapolis  0.982733
52                     Minneapolis  0.984764
53                     Minneapolis  0.982082
54      Second and Third precincts  0.972075

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Text 60: ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
By news@duluthnewstribune.com March 20, 2013 11:00 PM We are part of The Trust Project. A
former Itasca County sheriff's deputy pleaded guilty on Tuesday to trying to videotape a 17-year-old
girl as she entered and exited the shower. Aaron Edward Apitz, 45, of Deer River
was charged earlier this month with one felony count of interference with privacy against a
minor. An investigation revealed in February that Apitz allegedly tried to videotape the girl in
the bathroom. The teen discovered the phone and reviewed the video, which showed that Apitz
had placed the phone in the bathroom. According to the Grand Rapids Herald Review, Apitz
admitted to setting up an iPhone under a bathroom vanity with the intent of capturing
the teenage girl disrobing. Apitz resigned from his position with the Itasca County Sheriff's office
on March 5. Defense attorney John Undem confirmed that Apitz accepted a plea agreement. The
agreement calls for Apitz to be sentenced on a stay of NEWS Ex-Itasca County deputy
pleads guilty to trying to record girl in shower A former Itasca County sheri's deputy
pleaded guilty on Tuesday to trying to videotape a 17-year-old girl as she entered and
exited the shower. Aaron Edward Apitz, 45, of Deer River was charged earlier this month
with one felony count of interf... Ex-Itasca County deputy pleads guilty to trying to record
girl in shower... https://www.duluthnewstribune.com/news/ex-itasca-county-deputy-plea... 1 of 2 11/25/2022, 7:59 PM imposition with the following conditions:
He will serve 15 days in the Aitkin County Jail before sentencing; pay $1,085 in
fines; be placed on two years of probation; have no contact with the victim; undergo
a pre- sentence investigation and a psychiatric evaluation; and submit a DNA sample. Prosecutor Christopher
Strandlie says that the investigation is still ongoing and, as part of the plea agreement,
if anything else is discovered regarding Apitz he can still be charged. District Court Judge
Charles H. LeDuc scheduled sentencing for May 17. RELATED TOPICS: CRIME POLICE Ex-Itasca County deputy
pleads guilty to trying to record girl in shower... https://www.duluthnewstribune.com/news/ex-itasca-county-deputy-plea... 2 of 2 11/25/2022, 7:59
PM

-------------------------------------------------- Dates: --------------------------------------------------

      entities    scores
36  2013-03-20  0.999991
37  2022-11-25  0.999202
38  2022-11-25  0.970088

-------------------------------------------------- Locations: --------------------------------------------------

                           entities    scores
128              Aitkin County Jail  0.994003
129                      Deer River   0.98785
130                      Deer River   0.99456
131                Ex-Itasca County  0.988427
132                Ex-Itasca County  0.991907
133                Ex-Itasca County  0.989372
134                    Grand Rapids  0.911007
135                   Itasca County  0.992883
136                   Itasca County  0.991476
137  Itasca County Sheriff's office  0.897671

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Text 59: ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C C STATE OF MINNESOTA BOARD OF PEACE OFFICER STANDARDS AND TRAINING Re: PB 14-007
ORDER FOR In the maker of Aaron Edward Apitz AUTOMATIC REVOCATION Peace Officer License: 11506
1. The Minnesota Board of Peace Officer Standards and Training ("Board') is authorized pursuant to
Minnesota Statutes sections 626.84 through 626.90 (2000) and Minnesota Rules 6700 to license, regulate and
discipline persons who apply for, petition, or hold peace officer licenses in the State of
Minnesota and is further authorized pursuant to Minnesota Statutes section 214.10 to review complaints against
peace officers and to initiate appropriate disciplinary action. 2. Aaron Edward Apitz ("Respondent") has been
a peace officer in Minnesota since October 7, 1992. 3. Pursuant to Minnesota Statutes section
626,8431, the license of a peace officer convicted of a felony-level offense is automatically revoked.
Under this statute, "conviction" includes a finding of guilt, whether or not the adjudication of
guilt includes a finding of guilt, or whether or not the adjudication of guilt is
stayed or executed, an admission of guilt, or a no contest plea. 4. The Board
has received information indicating the Respondent was sentenced on a felony-level criminal conviction on July
1, 2013 as evidenced by a certified copy of the complaint, and sentencing order, which
are attached hereto and incorporated herein. C I NOW THEREFORE pursuant to the above recitals,
the Board issues the following: 1. IT IS HEREBY ORDERED that the Respondent's peace officer
license in the state of Minnesota is automatically REVOKED pursuant to Minnesota Statutes section 626.8431.
During this period of revocation, Respondent shall not in any manner practice or hold himself
out as a peace officer in this state. The revocation shall take effect immediately. 2.
IT IS FURTHER ORDERED that the Respondent shall surrender their peace officer license to the
Board immediately. The license shall be forwarded to the Board of Peace Officer Standards and
Training, 1600 University Avenue West, Suite 200, Saint Paul, Minnesota 551 04-3825. 3. IT IS
FURTHER ORDERED that the terms of this order are adopted and implemented on this /3
day of /k/%!it 20!D MINNESOTA BOARD OF PEACE OFFICER STANDARDS AND TRAINING NEIL W. MELTON
Executive Director, Board of Peace Officer Standards and Training AG: 435993v. 01

-------------------------------------------------- Dates: --------------------------------------------------

      entities    scores
35  1992-10-07  0.999991

-------------------------------------------------- Locations: --------------------------------------------------

                        entities    scores
115  1600 University Avenue West  0.916598
116              MINNESOTA BOARD  0.875349
117              MINNESOTA BOARD  0.707735
118                    Minnesota  0.528818
119              Minnesota Board  0.915242
120              Minnesota Rules  0.724092
121           Minnesota Statutes  0.786359
122           Minnesota Statutes  0.614137
123           Minnesota Statutes  0.837282
124              Minnesota since  0.872052
125    Saint Paul, Minnesota 551  0.943137
126           State of Minnesota  0.980165
127           state of Minnesota  0.666055

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Text 31: ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
City of Minneapolis Request for Committee Action To: Ways & Means Date: 9/8/2015 From: City
Attorney's Office Prepared by: Kristin Sarff Presented by: Susan Segal File type: Action Subcategory: Settlement
Subject: Settlement of a lawsuit by Louis Tate. Description: Approving the settlement of the lawsuit
of Louis Tate by payment of $25,000.00 to Louis Tate and his attorneys from Fund/Org.
06900 1500100 145400, and authorize the City Attorney's Office to execute any documents necessary to
effectuate settlement. Previous Actions: None Ward/Neighborhood/Address: Ward 9 Midtown Phillips Intersection of 14th Avenue South
and 24th Street East Background/Analysis: Plaintiff alleges causes of action for excessive force, assault, and
battery. The parties have negotiated a proposed settlement in the amount of $25,000.00, including all
claims for damages, attorneys' fees and costs. The City Attorney's Office and MPD administration believe
that the proposed settlement is in the best interests of the City and recommend approval
by this Committee and the City Council. Financial Review: No additional appropriation required, amount included
in current budget. ☐ Future budget impact anticipated. ☐ Approved by the Permanent Review Committee.
☐ Meets Small and Underutilized Business Program goals. Attachments: 1. None

-------------------------------------------------- Dates: --------------------------------------------------

      entities    scores
17  2015-09-08  0.999992

-------------------------------------------------- Locations: --------------------------------------------------

,entities,scores
39,City,0.69173
40,City Attorney's Office,0.983732
41,City Attorney's Office,0.953165
42,City Attorney's Office,0.882677
43,City of Minneapolis,0.94624
44,Ward 9 Midtown Phillips Intersection of 14th Avenue South and 24th Street East,0.975901

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Text 1: ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Hennepin County 300 South Sixth Street, Minneapolis, MN 55487 DATE: December 21, 2021 TO: Detention
Deputy Guled Abdullahi FROM: Assistant County Administrator Mark Thompson RE: Written Reprimand You are receiving
a written reprimand for your failure to follow Hennepin County's COVID-19 Vaccination and Testing Policy.
Hennepin County has sent regular and ongoing communication regarding the policy expectation of being fully
vaccinated or complying with weekly COVID testing. During the week of October 11-16, 2021 you
failed to provide proof: • Of your vaccination status, or • That you had taken
a COVID test and provided your test results Due to the seriousness of your failure
to follow directives and abide by the county's vaccination and testing policy, you are being
issued this written reprimand. It is my hope that you will take advantage of this
opportunity to correct your behavior so that you may succeed in this position. Please note
that continued incidents of this nature or a similar nature may result in additional, more
serious disciplinary action up to and including termination. If you wish to appeal this action,
your rights and the procedures are contained in the Labor Agreement between Hennepin County and
the Minnesota Public Employees Association. Cc: Manager HR Business Partner Labor Relations Representative Payroll Contact
Employee HR File

-------------------------------------------------- Dates: --------------------------------------------------

     entities    scores
3  2021-12-21  0.999994

-------------------------------------------------- Locations: --------------------------------------------------

                                                entities    scores
5                                                  55487  0.760508
6                                     Hennepin  County's  0.993168
7                                        Hennepin County  0.995854
8                                        Hennepin County  0.988137
9   Hennepin County  300 South Sixth Street, Minneapolis  0.978387
10                                      Minnesota Public  0.835993

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Text 0: ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Home Legislative File 2021-01132 RCA Legal selement: Workers' Compensaon claim of Andrew Allen (RCA-2021-01206) ORIGINATING
DEPARTMENT Finance & Property Services To Commiee(s) # Commiee Name Meeng Date 1 Policy &
Government Oversight Commiee Oct 20, 2021 LEAD STAFF: Emily Ann Colby PRESENTED BY: Emily Ann
Colby Acon Item(s) # File Type Subcategory Item Descripon 1 Acon Selement Approving the selement
of the Workers' Compensaon claim of Andrew Allen, by payment of $170,000 to Andrew Allen
and aorney, Meuser Law Firm, and authorizing the City Aorney's Office to execute any documents
necessary to effectuate the selement. Previous Acons None RCA-2021-01206 - Legal settlement: Workers' Compensation claim
of ... https://lims.minneapolismn.gov/RCA/8755 1 of 2 12/4/2021, 1:33 AM Ward / Neighborhood / Address #
Ward Neighborhood Address 1. Not Applicable Background Analysis City of Minneapolis employee sustained work-related injuries.
The pares reached a tentave selement of $170,000 over three years from fund 06930-1450100-789401-145400. Risk
Management believes this selement is in the best interests of the City and recommends approval
by the Commiee and the City Council. FISCAL NOTE • Legal selement: Workers' Compensaon claim
of Andrew Allen - Fiscal Note RCA-2021-01206 - Legal settlement: Workers' Compensation claim of ...
https://lims.minneapolismn.gov/RCA/8755 2 of 2 12/4/2021, 1:33 AM

-------------------------------------------------- Dates: --------------------------------------------------

     entities    scores
0  2021-10-20  0.999993
1  2021-12-04  0.999784
2  2021-12-04  0.999633

-------------------------------------------------- Locations: --------------------------------------------------

                      entities    scores
0         City Aorney's Office  0.882122
1          City of Minneapolis  0.924146
2                   Government  0.511303
3                 Neighborhood  0.571632
4  Ward Neighborhood Address 1  0.754386

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Text 17: ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Home Legislative File 2021-01180 RCA Legal selement: Workers' Compensaon claim of Mahew Alberts (RCA-2021-01256) ORIGINATING
DEPARTMENT Finance & Property Services To Commiee(s) # Commiee Name Meeng Date 1 Policy &
Government Oversight Commiee Nov 3, 2021 LEAD STAFF: Emily Ann Colby PRESENTED BY: Emily Ann
Colby Acon Item(s) # File Type Subcategory Item Descripon 1 Acon Selement Approving the selement
of the Workers' Compensaon claim of Mahew Alberts, by payment of $155,000 to Mahew Alberts
and aorney, Meuser Law Firm, and authorizing the City Aorney's Office to execute any documents
necessary to effectuate the selement. Previous Acons None RCA-2021-01256 - Legal settlement: Workers' Compensation claim
of M... https://lims.minneapolismn.gov/RCA/8821 1 of 2 12/4/2021, 1:48 AM Ward / Neighborhood / Address #
Ward Neighborhood Address 1. Not Applicable Background Analysis City of Minneapolis employee sustained work-related injuries.
The pares reached a tentave selement by payment of $155,000 from fund 06930-1450100-789401-145400. Risk Management
believes this selement is in the best interests of the City and recommends approval by
the Commiee and by the City Council. FISCAL NOTE • Legal selement: Workers' Compensaon claim
of Mahew Alberts - Fiscal Note RCA-2021-01256 - Legal settlement: Workers' Compensation claim of M...
https://lims.minneapolismn.gov/RCA/8821 2 of 2 12/4/2021, 1:48 AM

-------------------------------------------------- Dates: --------------------------------------------------

      entities    scores
11  2021-11-03  0.999994
12  2021-12-04  0.999946
13  2021-12-04  0.999888

-------------------------------------------------- Locations: --------------------------------------------------

                       entities    scores
24         City Aorney's Office  0.869129
25          City of Minneapolis   0.92546
26                   Meuser Law  0.512247
27                 Neighborhood  0.617445
28  Ward Neighborhood Address 1  0.794325

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Text 53: ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Home Legislative File 2022-00178 RCA Legal Selement: Workers' Compensaon claim of Brian Anderson (RCA-2022-00173) ORIGINATING
DEPARTMENT Finance & Property Services To Commiee(s) # Commiee Name Meeng Date 1 Policy &
Government Oversight Commiee Feb 22, 2022 LEAD STAFF: Emily Ann Colby PRESENTED BY: Emily Ann
Colby Acon Item(s) # File Type Subcategory Item Descripon 1 Acon Selement Approving the workers'
compensaon claim of Brian Anderson by payment of $197,500 over four years to Brian Anderson
and aorney, Ashley Biermann, and authorizing the City Aorney's Office to execute any documents necessary
to effectuate the selement. Ward / Neighborhood / Address # Ward Neighborhood Address 1. Not
Applicable Background Analysis City of Minneapolis employee sustained work-related injuries. The pares reached a tentave
selement by payment of $197,500 over four years from fun 06930-1450100-789401-145400. Risk Management believes the
selement is in the best interests of the City and recommends approval by the Commiee
and the City Council FISCAL NOTE • Legal Selement: Workers' Compensaon claim of Brian Anderson
- Fiscal Note RCA-2022-00173 - Legal Settlement: Workers' Compensation claim of... https://lims.minneapolismn.gov/RCA/9298 1 of 1
3/18/2022, 9:48 PM

-------------------------------------------------- Dates: --------------------------------------------------

      entities    scores
31  2022-02-22  0.999993
32  2022-03-18  0.999968

-------------------------------------------------- Locations: --------------------------------------------------

                                  entities    scores
101                   City Aorney's Office  0.924588
102                    City of Minneapolis   0.78715
103  Policy & Government Oversight Commiee  0.707078
104                               Property  0.579967
105                    Ward / Neighborhood  0.766024
106            Ward Neighborhood Address 1  0.891331

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Text 63: ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Home Legislative File 2022-00238 RCA Legal Selement: Workers' Compensaon claim of Sherry Appledorn (RCA-2022-00188) ORIGINATING
DEPARTMENT Finance & Property Services To Commiee(s) # Commiee Name Meeng Date 1 Policy &
Government Oversight Commiee Mar 7, 2022 LEAD STAFF: Emily Ann Colby PRESENTED BY: Emily Ann
Colby Acon Item(s) # File Type Subcategory Item Descripon 1 Acon Selement Approving the workers'
compensaon claim of Sherry Appledorn by payment of $160,000 over two years to Sherry Appledorn
and aorney, Meuser Law Firm, and authorizing the City Aorney's Office to execute any documents
necessary to effectuate the selement. Ward / Neighborhood / Address # Ward Neighborhood Address 1.
Not Applicable Background Analysis City of Minneapolis employee sustained work-related injuries. The pares reached a
tentave selement of $160,000 paid over two years from fund 06930-1450100-789401-145400. Risk Management believes this
selement is in the best interests of the City and recommends approval by the Commiee
and the City Council. FISCAL NOTE • Legal Selement: Workers' Compensaon claim of Sherry Appledorn
- Fiscal Note RCA-2022-00188 - Legal Settlement: Workers' Compensation claim o... https://lims.minneapolismn.gov/RCA/9315 1 of 1
3/18/2022, 9:59 PM

-------------------------------------------------- Dates: --------------------------------------------------

      entities    scores
39  2022-03-07  0.999994
40  2022-03-18   0.99995

-------------------------------------------------- Locations: --------------------------------------------------

                        entities    scores
138         City Aorney's Office  0.891643
139          City of Minneapolis  0.872292
140                      Commiee  0.513522
141          Ward / Neighborhood  0.775238
142  Ward Neighborhood Address 1  0.918567

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Text 14: ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Home Legislative File 2022-00239 RCA Legal Selement: Workers' Compensaon claim of Ellen Allen (RCA-2022-00187) ORIGINATING
DEPARTMENT Finance & Property Services To Commiee(s) # Commiee Name Meeng Date 1 Policy &
Government Oversight Commiee Mar 7, 2022 LEAD STAFF: Emily Ann Colby PRESENTED BY: Emily Ann
Colby Acon Item(s) # File Type Subcategory Item Descripon 1 Acon Selement Approving the workers'
compensaon claim of Ellen Allen by payment of $150,000 over two years to Ellen Allen
and aorney, Meuser Law Firm, and authorizing the City Aorney's Office to execute any documents
necessary to effectuate the selement. Ward / Neighborhood / Address # Ward Neighborhood Address 1.
Not Applicable Background Analysis City of MInneapolis employee sustained work-related injuries. The pares reached a
tentave selement by payment of $150,000 over two years from fund 06930-1450100-789401-145400. Risk Managment believes
this selement is in the best interests of the City and recommends approval by the
Commiee and the City Council. FISCAL NOTE • Legal Selement: Workers' Compensaon claim of Ellen
Allen - Fiscal Note RCA-2022-00187 - Legal Settlement: Workers' Compensation claim of... https://lims.minneapolismn.gov/RCA/9314 1 of
1 3/18/2022, 10:00 PM

-------------------------------------------------- Dates: --------------------------------------------------

      entities    scores
9   2022-03-07  0.999994
10  2022-03-18  0.999938

-------------------------------------------------- Locations: --------------------------------------------------

                       entities    scores
19         City Aorney's Office  0.894849
20          City of MInneapolis  0.770196
21                      Commiee  0.581368
22          Ward / Neighborhood  0.739963
23  Ward Neighborhood Address 1  0.897244

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Text 57: ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Itasca Co. sheriff's deputy charged with videotaping girl in bathroom Associated Press MARCH 7, 2013
— 9:02AM GRAND RAPIDS, Minn. - An Itasca County sheriff's deputy is accused of trying
to videotape a teenage girl using the bathroom at his home. The Minnesota Bureau of
Criminal Apprehension alleges 45-year-old Aaron Apitz, of Deer River, used his work cellphone to try
to videotape the girl entering and exiting the shower. A criminal complaint says the girl
found the phone and saw it was recording and reported the incident. The Duluth News
Tribune ( http://bit.ly/Zisb9M (http://bit.ly/Zisb9M) ) says Apitz resigned Tuesday. He was charged with felony interference
with privacy against a minor on Wednesday. Apitz is not in custody. He could not
be reached for comment because his phone number has not been published. ___ Information from:
Duluth News Tribune, http://www.duluthsuperior.com (http://www.duluthsuperior.com) Itasca Co. sheriff's deputy charged with videotaping girl in bathroom
https://www.startribune.com/itasca-co-sheriff-s-deputy-charged-with-vi... 1 of 1 11/25/2022, 7:59 PM

-------------------------------------------------- Dates: --------------------------------------------------

      entities    scores
33  2013-03-07  0.999986
34  2022-11-25   0.99999

-------------------------------------------------- Locations: --------------------------------------------------

               entities    scores
107          Deer River  0.993573
108         Duluth News  0.779399
109         Duluth News  0.667339
110  GRAND RAPIDS, Minn    0.9778
111           Itasca Co   0.99354
112           Itasca Co  0.883656
113       Itasca County  0.994637
114    Minnesota Bureau  0.796551

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Text 25: ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Minneapolis Police Officers: 350 S. 5th St. Minneapolis, MN 55415 Dear Everyone - but especially
Minneapolis citizens, An Open Letter to express what the vast majority of Minneapolis Police Officers
feel at this moment. We wholeheartedly condemn Derek Chauvin. We Are With You in the
denouncement of Derek Chauvin's actions on Memorial Day, 2020. Like us, Derek Chauvin took an
oath to hold the sanctity of life most precious. Derek Chauvin failed as a human
and stripped George Floyd of his dignity and life. This is not who we are.
We Are With You and want to communicate a sentiment that is broad within our
ranks. We ask that our voices be heard. We are leaders, formal and informal, and
from all ranks within the Minneapolis Police Department. We're not the union or the administration.
We are officers who represent the voices of hundreds of other Minneapolis Police Officers. Hundreds.
We acknowledge that Chief Arradondo needs each of us to dutifully follow him while he
shows us the way. We stand ready to listen and embrace the calls for change,
reform and rebuilding. We Are With You moving forward. We want to work with you
and for you to regain your trust. Sincerely, Minneapolis Police Officers: Mark Klukow Charlie Adams
Darcy Klund Christie Nelson Nick Torborg Mike Kirchen Pete Stanton Gary Nelson Rich Jackson Mohamed
Abdullahi Molly Fischer Steve McCarty John Delmonico Richard Zimmerman The above letter represents our statement
in whole. We will not be having an additional comment or allowing additional interviews. Thank
you for giving us voice.

-------------------------------------------------- Dates: --------------------------------------------------

   entities scores
14      NaN    NaN

-------------------------------------------------- Locations: --------------------------------------------------

                                  entities    scores
29  350 S. 5th St.   Minneapolis, MN 55415  0.917484
30                            George Floyd  0.564408
31                             Minneapolis  0.988595
32                             Minneapolis  0.944266
33                             Minneapolis  0.920805
34                             Minneapolis  0.969332
35                             Minneapolis  0.960646
36                     Minneapolis  Police   0.81869

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Text 26: ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
OAO450 (Rev. 5/85) Judgment in a Civil Case UNITED STATES DISTRICT COURT District of Minnesota
Daniel L. Fancher JUDGMENT IN A CIVIL CASE V. Case Number: 13-cv-435(DSD/JJK) Sokhom Klann and
Andrew Allen, in their individual capacities as officers of the Minneapolis Police Department Jury Verdict.
This action came before the Court for a trial by jury. The issues have been
tried and the jury has rendered its verdict. X Decision by Court. This action came
to trial or hearing before the Court. The issues have been tried or heard and
a decision has been rendered. IT IS ORDERED AND ADJUDGED THAT: 1. The court adopts
the verdict of the jury; 2. Judgment is in favor of Fancher on the excessive
force claim and against defendant Klann in the amount of $27,640; 3. The jury found
for defendants on Fancher's unreasonable search and seizure claim; 4. The jury found for defendants
on Fancher's unreasonable seizure and false arrest claim; 5. The motion by plaintiff Fancher for
judgment as a matter of law on his unreasonable search and seizure claim is denied;
6. The motion by plaintiff Fancher for judgment as a matter of law on his
unreasonable seizure and false arrest claim is denied; 7. The motion by defendant Klann on
Fancher's excessive force claim is denied; 8. The remaining motions by plaintiff and defendants for
judgment as a matter of law are denied as moot. November 24, 2014 RICHARD D.
SLETTEN, CLERK Date s/L. Brennan (By) L. Brennan, Deputy Clerk CASE 0:13-cv-00435-DSD-JJK Document 75 Filed
11/24/14 Page 1 of 1

-------------------------------------------------- Dates: --------------------------------------------------

      entities    scores
15  2014-11-24  0.999993
16  2014-11-24  0.999994

-------------------------------------------------- Locations: --------------------------------------------------

                                                     entities    scores
37                              Minneapolis Police Department  0.922979
38  UNITED STATES DISTRICT COURT District of Minnesota Daniel  0.955617

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Text 45: ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
OAO450 (Rev. 5/85) Judgment in a Civil Case UNITED STATES DISTRICT COURT District of Minnesota
Darrell Williams and Cymonne Williams, Plaintiffs, JUDGMENT IN A CIVIL CASE V. Case Number: 10-2092
ADM/TNL Sergeant David Voss, Sergeant Mark Sletta, Officer Brandon Kitzerow, Officer Mark Durand, Officer Shawn
Williams, Officer Jeff Kading, Officer Lonnie Hoffbeck, Officer Peter Rud, Officer Kevin Angerhoffer, Sergeant Brian
Anderson, in their official and individual capacities, and the City of Minneapolis, Defendants. Jury Verdict.
This action came before the Court for a trial by jury. The issues have been
tried and the jury has rendered its verdict. X Decision by Court. This action came
to trial or hearing before the Court. The issues have been tried or heard and
a decision has been rendered. IT IS ORDERED AND ADJUDGED THAT: Plaintiffs' Complaint in this
matter is dismissed with prejudice and without costs and disbursements to any party. January 23,
2012 RICHARD D. SLETTEN, CLERK Date s/ J. Zuech (By) J. Zuech Deputy Clerk C:\Documents
and Settings\zuech\Desktop\Blank Judgment Form.wpd Form Modified: 09/16/04 CASE 0:10-cv-02092-ADM-TNL Doc. 38 Filed 01/23/12 Page 1
of 1

-------------------------------------------------- Dates: --------------------------------------------------

      entities    scores
24  2004-09-16  0.999981
25  2012-01-23  0.999993

-------------------------------------------------- Locations: --------------------------------------------------

                                                      entities    scores
72                                         City of Minneapolis  0.967181
73  UNITED STATES DISTRICT COURT District of Minnesota Darrell  0.927013

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Text 65: ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Too_LongOPCR Case #17-03832 Table of Contents 1. Table of Contents 2. Minneapolis Police Department Form
#3401 3. Investigative Summary 4. Statement of Sergeant Ali 5. Watch Commander's Log 6. MPD
Preliminary Incident Report 7. CAPRS MP 17-049029 8. Inform Browser (VISINET) 17-049029 a. VISINET AVL
Data 9. Minnesota State Accident Report 10. MPD Accident Review Findings 11. Crash Data Retrieval
(CDR ) Records 12. Route Map 13. Scene Photographs 14. Media Files a. Video from
MPD SIC b. MECC Audio Capture 15. Workforce Director Off-Duty Records 16. Minneapolis Police Department
Policy & Procedures 17. Employee Profile CUAPB002647

-------------------------------------------------- Dates: --------------------------------------------------

   entities scores
41      NaN    NaN

-------------------------------------------------- Locations: --------------------------------------------------

               entities    scores
143          MPD SIC  b   0.78353
144  Minneapolis Police  0.806397
145  Minneapolis Police  0.862937
146     Minnesota State  0.784632